### ISSUE TITLE
gem spell slots

### ISSUE THREAD

**Issue by Grimmspecter** [meeprdib/Apotheosis-Ascended#12]
instead of having pre assigned spells some way to add spells to the gems themselves(per gems element so blood spell blood gem) maybe have it +1 the level then a config to dictate the number of allowed spells in a gem

**Comment by Grimmspecter** [comment]
alternate option have a config that allows gems to roll with random spells of their type and config will say max number of spells so if 3 no change if 2 will select 2 out of the pool ect ect

**Comment by meeprdib** [comment]
There are already gems that add to spell levels, and it's impossible with the current system to "randomize" which attributes that gems have, that'd be more suited for the affix system.
