### ISSUE TITLE
Tetra integration.

### ISSUE THREAD

**Issue by taitep** [meeprdib/Apotheosis-Ascended#30]
Integration with tetra to make affix gear out of tetra stuff would be cool, as otherwise you sorta need to pick tetra or apotheosis. Should be doable, but there might be some problems with the fact that a tool can switch its tool type, but it should be doable.

**Comment by meeprdib** [comment]
You can set overrides to set Tetra tools via the adventure.cfg config if they aren't immediately picked up by Apotheosis. It's up to Tetra to define its tools correctly, anyway. Additionally, I have neither the skillset nor interest to work with Tetra due to it be being closed source ARR licensed.
