### ISSUE TITLE
Rendering gem crashes game

### ISSUE THREAD

**Issue by ScarlettFrost** [meeprdib/Apotheosis-Ascended#31]
A specific gem, one which I cannot tell, seems to crash my game whenever it tries to load the model/texture. I don't have much information aside from this and the crash log.

[crash-2024-12-22_12.38.38-client.txt](https://github.com/user-attachments/files/18222872/crash-2024-12-22_12.38.38-client.txt)

**Comment by meeprdib** [comment]
Solved in the Discord server, this was the fault of "Beautiful Enchanted Books" mod
